export const ADAS_LABELS = {
  workflow_ui: [
    { en: "Task ID", cn: "任务编号" },
    { en: "Batch Progress", cn: "批次进度" },
    { en: "Workflow", cn: "工作流程" },
    { en: "Submission", cn: "提交/交付" },
    { en: "Viewport", cn: "主视图/视口" },
    { en: "Toolbar", cn: "工具栏" },
    { en: "Attributes Panel", cn: "属性配置面板" },
    { en: "Timeline", cn: "时间轴" },
    { en: "Keyframe", cn: "关键帧" },
    { en: "Annotate", cn: "标注/打标签" },
    { en: "Review", cn: "质检/审核" },
    { en: "Reject", cn: "驳回" },
    { en: "Accept", cn: "验收" },
  ],
  technical_tools: [
    { en: "Ground Truth", cn: "真值/基准事实" },
    { en: "Lidar", cn: "激光雷达" },
    { en: "Point Cloud", cn: "点云" },
    { en: "Calibration", cn: "标定/校准" },
    { en: "Ego Vehicle", cn: "主车/自车" },
    { en: "Sensor Fusion", cn: "传感器融合" },
    { en: "Field of View (FOV)", cn: "视角/视野" },
    { en: "Inertial Measurement Unit (IMU)", cn: "惯性测量单元" },
    { en: "Global Positioning System (GPS)", cn: "全球定位系统" },
    { en: "Radar", cn: "毫米波雷达" },
  ],
  objects: [
    { en: "Passenger Car", cn: "乘用车" },
    { en: "Light Truck", cn: "轻型卡车" },
    { en: "Heavy Truck", cn: "重型卡车" },
    { en: "Motorcycle", cn: "摩托车" },
    { en: "Bicycle", cn: "自行车" },
    { en: "Pedestrian", cn: "行人" },
    { en: "Construction Vehicle", cn: "工程车辆" },
    { en: "Emergency Vehicle", cn: "应急车辆 (救护车/警车)" },
    { en: "Trailer", cn: "挂车" },
    { en: "Van", cn: "面包车/厢式货车" },
  ],
  attributes: [
    { en: "Occluded", cn: "被遮挡" },
    { en: "Truncated", cn: "被截断 (在画面边缘)" },
    { en: "Partial", cn: "部分遮挡" },
    { en: "Full", cn: "完全遮挡" },
    { en: "Orientation", cn: "朝向 (角度)" },
    { en: "Bounding Box", cn: "包围框" },
    { en: "Polygon", cn: "多边形" },
    { en: "Polyline", cn: "折线" },
    { en: "Semantic", cn: "语义分割" },
    { en: "Cuboid", cn: "长方体 (3D)" },
    { en: "Vertex", cn: "顶点" },
  ],
  error_types: [
    { en: "False Positive", cn: "误报/虚警 (多标)" },
    { en: "False Negative", cn: "漏报 (漏标)" },
    { en: "Misclassification", cn: "类别错误" },
    { en: "Over-segmentation", cn: "过分割" },
    { en: "Under-segmentation", cn: "欠分割" },
    { en: "Localization Error", cn: "定位/位置错误" },
  ],
  infrastructure: [
    { en: "Traffic Light", cn: "红绿灯" },
    { en: "Traffic Sign", cn: "交通标志" },
    { en: "Lane Marking", cn: "车道线" },
    { en: "Curb", cn: "路缘" },
    { en: "Guardrail", cn: "护栏" },
    { en: "Pole", cn: "立柱" },
    { en: "Vegetation", cn: "植被" },
    { en: "Sidewalk", cn: "人行道" },
    { en: "Crosswalk", cn: "斑马线" },
    { en: "Speed Bump", cn: "减速带" },
  ],
  states: [
    { en: "Parked", cn: "静止/停放" },
    { en: "Moving", cn: "移动中" },
    { en: "Turning Left", cn: "左转" },
    { en: "Braking", cn: "刹车中" },
    { en: "Overtaking", cn: "超车" },
    { en: "Yielding", cn: "让行" },
  ],
  environment: [
    { en: "Daylight", cn: "白昼" },
    { en: "Foggy", cn: "雾天" },
    { en: "Rainy", cn: "雨天" },
    { en: "Night", cn: "夜晚" },
    { en: "Tunnel", cn: "隧道" },
    { en: "Overcast", cn: "阴天" },
  ],
  workflow_status: [
    { en: "In Progress", cn: "进行中" },
    { en: "Pending Review", cn: "待审核" },
    { en: "Rework Required", cn: "需要返工" },
    { en: "Quality Check (QC)", cn: "质量检测" },
    { en: "Approved", cn: "已批准/通过" },
    { en: "Final Delivery", cn: "最终交付" },
  ]
};
